apiVersion: apps/v1
kind: Deployment
metadata:
  name: rectangler
  labels:
    app: rectangler
spec:
  selector:
    matchLabels:
      app: rectangler
  template:
    metadata:
      labels:
        app: rectangler
        tier: web
    spec:
      containers:
      - name: rectangler
        image: rectangler
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: rectangler
  labels:
    app: rectangler
spec:
  ports:
    - port: 80
      targetPort: 8085
      protocol: TCP
  selector:
    app: rectangler
