apiVersion: apps/v1
kind: Deployment
metadata:
  name: render
  labels:
    app: render
spec:
  selector:
    matchLabels:
      app: render
  template:
    metadata:
      labels:
        app: render
        tier: web
    spec:
      containers:
      - name: render
        image: render
        ports:
        - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: render
  labels:
    app: render
spec:
  ports:
    - port: 80
      targetPort: 8084
      protocol: TCP
  selector:
    app: render
